# Generated by Django 5.2.4 on 2025-08-01 11:20

import adventure.mtb_tracks.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MtbTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('gps_file', models.FileField(blank=True, null=True, upload_to='MTB/mtb_tracks', validators=[adventure.mtb_tracks.validators.FileExtensionValidator(), adventure.mtb_tracks.validators.FileSizeValidator(10)])),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors_tracks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mtb_tracks.mtbtracks')),
            ],
        ),
        migrations.CreateModel(
            name='TrackImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='MTB/track_images', validators=[adventure.mtb_tracks.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png']), adventure.mtb_tracks.validators.FileSizeValidator(5)])),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mtb_tracks.mtbtracks')),
            ],
        ),
    ]
