# Generated by Django 5.2.4 on 2025-08-01 11:20

import adventure.mtb_tracks.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics', validators=[adventure.mtb_tracks.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png']), adventure.mtb_tracks.validators.FileSizeValidator(5)])),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
